## Plugin Skeleton defaults - USER: do NOT edit this file, edit the config.py copy created on first use
#
# Default settings all go here
default_settings = {
  "mybool": True,
  "mynum": 23,
  "mystring": "Please"
}
